"""
utils/formatter.py
==================
Turns the synthesis (markdown text from Gemini) into a real file:

  .docx -> Word document with proper headings
  .pptx -> slide deck, one section per slide (long sections continue on a new slide)
  .md   -> plain markdown

Everything is built in memory and returned as bytes for st.download_button.
"""

import datetime
import io
import re

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from pptx import Presentation
from pptx.dml.color import RGBColor as PRGB
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches as PIn, Pt as PPt

GREEN = (0x0F, 0x5C, 0x4D)
INK   = (0x17, 0x20, 0x26)
MUTED = (0x5B, 0x66, 0x70)


# ── Reading the markdown ──────────────────────────────────────────────────────

def parse_blocks(text: str) -> list:
    """
    Split markdown into blocks: ("h", text) heading, ("p", text) paragraph,
    ("ul", text) bullet item, ("ol", text) numbered item.
    """
    blocks, para = [], []

    def flush():
        if para:
            blocks.append(("p", " ".join(para)))
            para.clear()

    for raw in text.splitlines():
        line = raw.strip().replace("`", "")
        if not line:
            flush()
            continue
        if re.fullmatch(r"[-*_]{3,}", line):          # horizontal rule
            flush()
            continue

        m = re.match(r"^#{1,6}\s+(.*)$", line)
        if m:
            flush()
            blocks.append(("h", m.group(1).strip("* ").strip()))
            continue

        m = re.fullmatch(r"\*\*([^*]{1,80})\*\*:?", line)   # a line that is only bold
        if m:
            flush()
            blocks.append(("h", m.group(1).strip()))
            continue

        if re.fullmatch(r"references:?", line, re.I):
            flush()
            blocks.append(("h", "References"))
            continue

        m = re.match(r"^[-*•]\s+(.*)$", line)
        if m:
            flush()
            blocks.append(("ul", m.group(1)))
            continue

        m = re.match(r"^\d+[.)]\s+(.*)$", line)
        if m:
            flush()
            blocks.append(("ol", m.group(1)))
            continue

        para.append(line)

    flush()
    return blocks


_TOKEN = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*)")


def _add_runs(paragraph, text: str, style_run):
    """Add text to a paragraph, turning **bold** and *italic* into real formatting."""
    for part in _TOKEN.split(text):
        if not part:
            continue
        bold = italic = False
        if part.startswith("**") and part.endswith("**") and len(part) > 4:
            part, bold = part[2:-2], True
        elif part.startswith("*") and part.endswith("*") and len(part) > 2:
            part, italic = part[1:-1], True
        run = paragraph.add_run()
        run.text = part   # works for both Word and PowerPoint paragraphs
        style_run(run, bold, italic)


def _plain(text: str) -> str:
    return text.replace("**", "").replace("*", "")


# ── .docx ─────────────────────────────────────────────────────────────────────

def to_docx(query: str, synthesis: str) -> bytes:
    doc = Document()

    for section in doc.sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1.1)
        section.right_margin = Inches(1.1)

    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    def style_for(size, color=INK, force_bold=False):
        def apply(run, bold, italic):
            run.font.name = "Calibri"
            run.font.size = Pt(size)
            run.font.color.rgb = RGBColor(*color)
            run.bold = bold or force_bold
            run.italic = italic
        return apply

    # Title + date
    title = doc.add_heading(level=0)
    _add_runs(title, query, style_for(20, GREEN, force_bold=True))
    title.paragraph_format.space_after = Pt(4)

    meta = doc.add_paragraph()
    _add_runs(meta,
              f"Generated by AcadSynth on {datetime.date.today().strftime('%d %B %Y')}",
              style_for(9, MUTED))
    meta.paragraph_format.space_after = Pt(14)

    in_refs = False
    for kind, text in parse_blocks(synthesis):
        if kind == "h":
            in_refs = text.lower().startswith("reference")
            h = doc.add_heading(level=1)
            _add_runs(h, text, style_for(14, GREEN, force_bold=True))
            h.paragraph_format.space_before = Pt(16)
            h.paragraph_format.space_after = Pt(4)
        elif kind == "p":
            p = doc.add_paragraph()
            _add_runs(p, text, style_for(11))
            p.paragraph_format.space_after = Pt(8)
            p.paragraph_format.line_spacing = 1.15
        else:
            p = doc.add_paragraph(style="List Bullet" if kind == "ul" else "List Number")
            _add_runs(p, text, style_for(10 if in_refs else 11))
            p.paragraph_format.space_after = Pt(4)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


# ── .pptx ─────────────────────────────────────────────────────────────────────

def _split_sentences(text: str) -> list:
    parts = re.split(r"(?<=[.!?])\s+(?=[A-Z\[])", text)
    return [p.strip() for p in parts if p.strip()]


def _chunk(items: list, limit: int) -> list:
    """Group items so each group has at most `limit` characters (one slide)."""
    groups, current, size = [], [], 0
    for item in items:
        if current and size + len(item) > limit:
            groups.append(current)
            current, size = [], 0
        current.append(item)
        size += len(item)
    if current:
        groups.append(current)
    return groups


def to_pptx(query: str, synthesis: str) -> bytes:
    prs = Presentation()
    prs.slide_width = PIn(13.333)
    prs.slide_height = PIn(7.5)

    def top_bar(slide):
        bar = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, prs.slide_width, PIn(0.14))
        bar.fill.solid()
        bar.fill.fore_color.rgb = PRGB(*GREEN)
        bar.line.fill.background()

    # Title slide
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    top_bar(slide)
    box = slide.shapes.add_textbox(PIn(0.9), PIn(2.4), PIn(11.5), PIn(2.6))
    tf = box.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    r = p.add_run()
    r.text = query
    r.font.size, r.font.bold, r.font.color.rgb = PPt(34), True, PRGB(*GREEN)
    p2 = tf.add_paragraph()
    p2.space_before = PPt(14)
    r2 = p2.add_run()
    r2.text = f"AcadSynth, {datetime.date.today().strftime('%d %B %Y')}"
    r2.font.size, r2.font.color.rgb = PPt(14), PRGB(*MUTED)

    # Group the text into sections: heading + list of bullet strings
    sections, current = [], {"title": "Summary", "items": []}
    for kind, text in parse_blocks(synthesis):
        if kind == "h":
            if current["items"]:
                sections.append(current)
            current = {"title": text, "items": []}
        elif kind == "p":
            current["items"].extend(_split_sentences(text))
        else:
            current["items"].append(text)
    if current["items"]:
        sections.append(current)

    for sec in sections:
        is_refs = sec["title"].lower().startswith("reference")
        groups = _chunk(sec["items"], 900 if is_refs else 520)
        for n, group in enumerate(groups):
            slide = prs.slides.add_slide(prs.slide_layouts[1])  # Title and Content
            top_bar(slide)

            title_shape = slide.shapes.title
            title_shape.left, title_shape.top = PIn(0.7), PIn(0.45)
            title_shape.width, title_shape.height = PIn(11.9), PIn(1.0)
            ttf = title_shape.text_frame
            ttf.word_wrap = True
            tp = ttf.paragraphs[0]
            tp.alignment = PP_ALIGN.LEFT
            tr = tp.add_run()
            tr.text = sec["title"] + (" (continued)" if n else "")
            tr.font.size, tr.font.bold, tr.font.color.rgb = PPt(30), True, PRGB(*GREEN)

            body = slide.placeholders[1]
            body.left, body.top = PIn(0.7), PIn(1.7)
            body.width, body.height = PIn(11.9), PIn(5.2)
            btf = body.text_frame
            btf.word_wrap = True
            for i, item in enumerate(group):
                para = btf.paragraphs[0] if i == 0 else btf.add_paragraph()
                para.space_after = PPt(10)
                _add_runs(para, item,
                          lambda run, b, it, s=(16 if is_refs else 24):
                          (setattr(run.font, "size", PPt(s)),
                           setattr(run.font, "bold", b),
                           setattr(run.font, "italic", it),
                           setattr(run.font.color, "rgb", PRGB(*INK))))

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()


# ── .md ───────────────────────────────────────────────────────────────────────

def to_md(query: str, synthesis: str) -> bytes:
    date = datetime.date.today().strftime("%d %B %Y")
    md = f"# {query}\n\n*Generated by AcadSynth on {date}*\n\n---\n\n{synthesis}\n"
    return md.encode("utf-8")


# ── Dispatcher ────────────────────────────────────────────────────────────────

def _safe_name(query: str) -> str:
    """File name that is valid on Windows, Mac and Linux."""
    name = re.sub(r"[^\w\-]+", "_", query.strip())[:40].strip("_")
    return name or "synthesis"


def format_output(query: str, synthesis: str, fmt: str) -> tuple:
    """
    fmt is ".docx", ".pptx" or ".md".
    Returns (file_bytes, filename, mime_type).
    """
    stamp = datetime.date.today().strftime("%Y%m%d")
    base = f"{_safe_name(query)}_{stamp}"

    if ".docx" in fmt:
        return (to_docx(query, synthesis), f"{base}.docx",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
    if ".pptx" in fmt:
        return (to_pptx(query, synthesis), f"{base}.pptx",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation")
    return to_md(query, synthesis), f"{base}.md", "text/markdown"
